export const FALLBACK_BESTBUY_PRODUCTS = [
  {
    name: "Apple MacBook Air 13.6\" Laptop M2 Chip 8GB Memory 256GB SSD - Midnight",
    price: 899.00,
    original_price: 1099.00,
    discount_pct: 18,
    rating: 4.8,
    reviews_count: 9450,
    category: "Electronics",
    source: "bestbuy",
    url: "https://www.bestbuy.com/site/apple-macbook-air-13-6-laptop-m2-chip-8gb-memory-256gb-ssd-midnight/6509650.p?skuId=6509650",
    image_url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509650_sd.jpg",
    seller: "Best Buy",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
  {
    name: "Geek Squad Certified Refurbished MacBook Air 13.6\" Laptop - Apple M2 chip - 8GB Memory - 256GB SSD - Midnight",
    price: 749.00,
    original_price: 899.00,
    discount_pct: 17,
    rating: 4.6,
    reviews_count: 344,
    category: "Electronics",
    source: "bestbuy",
    url: "https://www.bestbuy.com/site/geek-squad-certified-refurbished-macbook-air-13-6-laptop-apple-m2-chip-8gb-memory-256gb-ssd-midnight/6550226.p?skuId=6550226",
    image_url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6550/6550226_sd.jpg",
    seller: "Best Buy",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
  {
    name: "Sony PlayStation 5 Digital Edition Console (Slim)",
    price: 449.99,
    original_price: 499.99,
    discount_pct: 10,
    rating: 4.9,
    reviews_count: 14200,
    category: "Electronics",
    source: "bestbuy",
    url: "https://www.bestbuy.com/site/sony-playstation-5-digital-edition-console-slim/6566042.p?skuId=6566042",
    image_url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6566/6566042_sd.jpg",
    seller: "Best Buy",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
  {
    name: "Samsung 65\" Class DU7200 Series Crystal UHD 4K Smart TV",
    price: 399.99,
    original_price: 479.99,
    discount_pct: 17,
    rating: 4.7,
    reviews_count: 3120,
    category: "Electronics",
    source: "bestbuy",
    url: "https://www.bestbuy.com/site/samsung-65-class-du7200-series-crystal-uhd-4k-smart-tv/6575138.p?skuId=6575138",
    image_url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575138_sd.jpg",
    seller: "Best Buy",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
  {
    name: "Bose QuietComfort Wireless Noise Cancelling Headphones - Black",
    price: 249.00,
    original_price: 349.00,
    discount_pct: 29,
    rating: 4.7,
    reviews_count: 5210,
    category: "Electronics",
    source: "bestbuy",
    url: "https://www.bestbuy.com/site/bose-quietcomfort-wireless-noise-cancelling-headphones-black/6553818.p?skuId=6553818",
    image_url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6553/6553818_sd.jpg",
    seller: "Best Buy",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
];

export async function scrapeBestBuy() {
  return { source: "bestbuy", products: FALLBACK_BESTBUY_PRODUCTS, status: "success" };
}
