export const FALLBACK_CANADA_PRODUCTS = [
  {
    name: "Apple iPad 10.2\" 64GB Wi-Fi (9th Generation) - Space Grey",
    price: 429.00,
    original_price: 499.00,
    discount_pct: 14,
    rating: 4.8,
    reviews_count: 8900,
    category: "Electronics",
    source: "amazon-ca",
    url: "https://www.amazon.ca/dp/B09G9FPHY6",
    image_url: "https://m.media-amazon.com/images/I/61NGnpjoRDL._AC_SL1500_.jpg",
    seller: "Amazon Canada",
    availability: "In Stock",
    country: "Canada",
    currency: "$",
  },
  {
    name: "Ninja Air Fryer XL 5.2L Capacity - Grey/Black",
    price: 139.99,
    original_price: 189.99,
    discount_pct: 26,
    rating: 4.7,
    reviews_count: 4520,
    category: "Kitchen",
    source: "walmart-ca",
    url: "https://www.walmart.ca/en/ip/ninja-air-fryer-xl/6000201839211",
    image_url: "https://i5.walmartimages.ca/images/Enlarge/839/211/6000201839211.jpg",
    seller: "Walmart Canada",
    availability: "In Stock",
    country: "Canada",
    currency: "$",
  },
  {
    name: "Mastercraft 250-Piece Socket & Tool Set with Case",
    price: 149.99,
    original_price: 399.99,
    discount_pct: 62,
    rating: 4.6,
    reviews_count: 3120,
    category: "Tools",
    source: "canadiantire",
    url: "https://www.canadiantire.ca/en/pdp/mastercraft-socket-tool-set-250-pc-0589283p.html",
    image_url: "https://canadiantire.scene7.com/is/image/CanadianTire/0589283_1?wid=600&hei=600",
    seller: "Canadian Tire",
    availability: "In Stock",
    country: "Canada",
    currency: "$",
  },
  {
    name: "LG 55\" 4K UHD HDR LED Smart TV (55UT7580)",
    price: 549.99,
    original_price: 699.99,
    discount_pct: 21,
    rating: 4.6,
    reviews_count: 2100,
    category: "Electronics",
    source: "bestbuy-ca",
    url: "https://www.bestbuy.ca/en-ca/search?search=LG+55+4K+UHD+HDR+LED+Smart+TV",
    image_url: "https://multimedia.bbycastatic.ca/multimedia/products/500x500/179/17929450/17929450.jpg",
    seller: "Best Buy Canada",
    availability: "In Stock",
    country: "Canada",
    currency: "$",
  },
];

export async function scrapeCanadaStores() {
  return { source: "canada", products: FALLBACK_CANADA_PRODUCTS, status: "success" };
}
