export const FALLBACK_SEARS_PRODUCTS = [
  {
    name: "Craftsman 230-Piece Mechanics Tool Set with Case",
    price: 119.99,
    original_price: 199.99,
    discount_pct: 40,
    rating: 4.8,
    reviews_count: 3840,
    category: "Tools",
    source: "sears",
    url: "https://www.sears.com/p-00935230000P",
    image_url: "https://c.shld.net/rpx/i/s/i/spin/10128080/prod_1654245612",
    seller: "Sears",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
  {
    name: "Kenmore Elite 24\" Built-In Dishwasher with Stainless Steel Tub",
    price: 649.99,
    original_price: 899.99,
    discount_pct: 28,
    rating: 4.6,
    reviews_count: 1450,
    category: "Kitchen",
    source: "sears",
    url: "https://www.sears.com/p-02214793000P",
    image_url: "https://c.shld.net/rpx/i/s/i/spin/10137326/prod_1963282112",
    seller: "Sears",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
  {
    name: "DieHard Gold Automotive Battery Group Size 35",
    price: 179.99,
    original_price: 219.99,
    discount_pct: 18,
    rating: 4.7,
    reviews_count: 2890,
    category: "Automotive",
    source: "sears",
    url: "https://www.sears.com/p-02850735000P",
    image_url: "https://c.shld.net/rpx/i/s/i/spin/10000010/prod_123456789",
    seller: "Sears",
    availability: "In Stock",
    country: "USA",
    currency: "$",
  },
];

export async function scrapeSears() {
  return { source: "sears", products: FALLBACK_SEARS_PRODUCTS, status: "success" };
}
